import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Static UUID for thread identification
  const threadId = "a1b2c3d4-e5f6-7890-1234-56789abcdef0";

  return (
    <html lang="en">
      <body className={"antialiased"}>
        <CopilotKit 
          publicLicenseKey="ck_pub_0bf34e683d53cc9de242ba5ea8efe015"
          runtimeUrl="/api/copilotkit" 
          agent="sample_agent"
          threadId={threadId}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
